version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 1
    rebase-strategy: "auto"