version: "3.9"
services:
  app:
    image: tilt.dev/express-app
    ports:
      - 3000:3000
      - 35729:35729
    environment:
      - NODE_ENV=development
      - ENV=development
      - PORT=3000
    command:
      sh -c 'npm run-script develop'

  app_prod:
    image: tilt.dev/express-app
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - ENV=production
      - PORT=3001
    command:
      sh -c 'npm run-script start'